#cambio
eureka:         #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-discovery:8082/eureka} # Registers the Gateway in Eureka Server

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
      discovery:
        locator:
          enabled: true #Enable de locator for the services in Eureka Server (Service Discovery)
          lowerCaseServiceId: true #Gets the service name from Eureka as a lowercase string

      routes:
        - id: order-microservicio-id #Order service route declaration
          uri: lb://order-microservicio
          predicates:
            - Path=/micro-service/** #Path to access the service


